- name: Install ntp
  yum:
    name: ntp
    state: latest

- name: Copy ntp.conf
  copy: 
    src: ntp.msra.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  when: "'msra' in inventory_hostname" 

- name: Copy ntp.conf
  copy: 
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  when: "'msra' not in inventory_hostname" 


- name: Start&enable ntp
  service:
    name: ntpd
    state: started
    enabled: yes
    

 
