---
- hosts: localhost
  remote_user: root
  strategy: free
  roles:
  - docker-swarm-inventory-check

- hosts: all
  remote_user: root
  strategy: free
  roles:
  - docker-ce    

- hosts: docker-swarm[0]
  remote_user: root
  roles:
  - docker-swarm-init

- hosts: docker-swarm[1:1000]
  remote_user: root
  roles:
  - docker-swarm-join
