---
- hosts: all
  remote_user: root
  strategy: free
  roles:
  - docker-ce
    

- hosts: docker-swarm-init
  remote_user: root
  roles:
  - docker-swarm

- hosts: docker-swarm-join
  remote_user: root
  roles:
  - docker-swarm-join

