- name: Check repo
  stat:
    path=/etc/yum.repos.d/docker-ce.repo
  register: docker_repo



- name: Install repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: docker_repo.stat.exists == False

- name: Install docker-ce
  yum:
    name: docker-ce
    state: latest

- name: Create dir /etc/docker
  file:
    path: /etc/docker
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Check that the /etc/docker/daemon.json exists
  stat:
    path: /etc/docker/daemon.json
  register: docker_config_file

- name: Copy daemon.json
  copy: 
    src: daemon.json.st
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  register: dockerconf
  when: docker_lvm_device is defined and docker_config_file.stat.exists == False

- name: Copy daemon.json
  copy: 
    src: daemon.json.reg
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  register: dockerconf
  when: docker_lvm_device is undefined and docker_insecure_registries is defined and docker_config_file.stat.exists == False


- name: Change daemon.json add storage
  lineinfile:
    path: /etc/docker/daemon.json
    regexp: '"dm.directlvm_device=/dev/md10",'
    line: '    "dm.directlvm_device={{ docker_lvm_device }}",'
  when: docker_lvm_device is defined and docker_config_file.stat.exists == False
  register: dockerconf


- name: Change daemon.json add registry
  lineinfile:
    path: /etc/docker/daemon.json
    regexp: '"insecure-registries"'
    line: '  "insecure-registries" : ["{{ docker_insecure_regestries }}"]'
  when:  docker_insecure_registries is defined and docker_config_file.stat.exists == True
  register: dockerconf


- name: Start&enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Restart docker
  service:
    name: docker
    state: restarted
  when: dockerconf.changed

