- name: Check swarm
  shell: docker node list | grep {{ inventory_hostname }} | awk '{print $4}'
  register: docker_node_list

- debug: msg="{{ docker_node_list.stdout }}"


- debug: msg="{{ hostvars['TOKEN_HOLDER']['token'] }}"

#- name: Check ip addr
#  shell: ip addr | grep {{ docker_swarm_ip_address }}
#  register: docker_swarm_init

- name: Join swarm
  shell: docker swarm join --token {{ swarm_token.stdout }} {{ docker_swarm_ip_address }}:2377
#  when: "docker_swarm_init.stdout=='' and 'Ready' not in docker_node_list.stdout"
  when: "'Ready' not in docker_node_list.stdout"

