- name: Check swarm
  shell: docker node list | grep {{ inventory_hostname }} | awk '{print $4}'
  register: docker_node_list

- debug: msg="{{ docker_node_list.stdout }}"

- name: Register token
  shell: ssh msc-001 -X "docker swarm join-token manager" | grep docker | awk '{print $5}'
  register: swarm_token

- name: Join swarm
  shell: docker swarm join --token {{ swarm_token.stdout }} 172.25.0.11:2377
  when: "'msc-001' not in inventory_hostname and 'Ready' not in docker_node_list.stdout"

