- name: Check swarm
  shell: docker node list | grep {{ inventory_hostname }} | awk '{print $4}'
  register: docker_node_list

- debug: msg="{{ docker_node_list.stdout }}"


- debug: msg="{{ hostvars['TOKENIP_HOLDER']['token'] }}"

- debug: msg="{{ hostvars['TOKENIP_HOLDER']['ip'] }}"

- name: Join swarm
  shell: docker swarm join --token {{ hostvars['TOKENIP_HOLDER']['token'] }} {{ hostvars['TOKENIP_HOLDER']['ip'] }}:2377
  when: "'Ready' not in docker_node_list.stdout"

