- name: Check swarm
  shell: docker node list | grep {{ inventory_hostname }} | awk '{print $4}'
  register: docker_node_list


- name: Check ip addr
  shell: ip addr | grep {{ docker_swarm_ip_address }}
  register: docker_swarm_init

- debug: msg="{{ docker_node_list.stdout }}"

- debug: msg="{{ docker_swarm_init.stdout }}"

- name: Init swarm
  shell: docker swarm init --advertise-addr {{ docker_swarm_ip_address }}
  when: "docker_swarm_init != ''  and 'Ready' not in docker_node_list.stdout"

- name: Register token
  shell: docker swarm join-token manager | grep docker | awk '{print $5}'
  register: swarm_token
  when: "docker_swarm_init.stdout != '' and 'Ready' in docker_node_list.stdout"

- name: "Add Token to dummy host"
  add_host:
    name:   "TOKEN_HOLDER"
    token:  "{{ swarm_token.stdout }}"

- debug: msg="{{ swarm_token.stdout }}"




